version: "3.0"
services:
  db-kattsu-web:
    #platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  wordpress-kattsu-web:
    #platform: linux/x86_64
    image: wordpress:latest
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    depends_on:
      - db-kattsu-web
    ports:
      - 8892:80
    environment:
      WORDPRESS_DB_HOST: db-kattsu-web
      WORDPRESS_DB_NAME: test
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: test

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db-kattsu-web
    ports:
      - 4043:80
    environment:
      PMA_HOST: db-kattsu-web
      PMA_USER: test
      PMA_PASSWORD: test